### ISSUE TITLE
Dúvida na utilização do try/catch

### ISSUE THREAD

**Issue by barbozafernando** [juniorpb/cidades-promise#2]
Opa, beleza Junior? Então cara, encontrei seu repo pelo repo da [BrasilAPI](https://github.com/filipedeschamps/BrasilAPI), e vi que vocês estão usando essa lib. Aí dando uma olhada no código me surgiu uma pequena dúvida.

Lá nas funções do controller, vc fazia a verificação se a UF e o DDD eram apenas 2 valores, ótimo, beleza. E logo depois, vc criou as funções que faziam o get dentro de um try/catch, qual a diferença de usar elas dentro e fora de um?

Ou sei lá, tipo, vai ver por ser uma biblioteca para outras pessoas usarem aí tem que ter o trycatch... bom, não sei, por isso estou te perguntando haha.

Trabalho como programador há uns 5 meses, e reparei que se fosse eu, com base no meu humilde conhecimento - hahaha - teria feito sem o trycatch, daí surgiu a minha dúvida.

Espero que possa me responder, abraço!

**Comment by juniorpb** [comment]
Olá, @barbozafernando , tudo  bem? 
Usa-se o try/catch para tratamentos de erros. Basicamente, você tenta fazer algo dentro do Try, se dê erro, será executado o bloco do Catch, assim você da seguimento a execução do código.

Vale a pena ver mais detalhes nesse [link](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/try...catch).
Bons estudos!

**Comment by barbozafernando** [comment]
Puts, é verdade, esqueci desse detalhe dos erros. Mas mesmo assim, obrigado amigo, boa semana pra você! Abraço.
