### ISSUE TITLE
[SUGESTÃO] Fonte alternativa de dados

### ISSUE THREAD

**Issue by magnobiet** [juniorpb/cidades-promise#3]
@juniorpb, parabéns pelo trabalho e por ter agregado ele ao [BrasilAPI](https://github.com/filipedeschamps/BrasilAPI).

Caso queira adicionar uma API alternativa de consulta, o IBGE tem _endpoints_ públicos de cidade e municípios.

Tenho os três _endpoints_ documentados no Postman caso queira dar uma olhadinha. Segue link: https://documenter.getpostman.com/view/38670/RWgwQb95

**Comment by juniorpb** [comment]
@magnobiet muito obrigado pela sugestão incrível da API IBGE, certamente irei usar essa fonte para novas funcionalidades.

- Caso você queira contribuir ainda mais, será muito bem vindo.

**Comment by magnobiet** [comment]
Com certeza @juniorpb.

Dei uma pesquisada aqui e achei a documentação com todos os _endpoints_ da API de localidades do IBGE, não sei se eles se aplicam aqui, mas fica de referência.

https://servicodados.ibge.gov.br/api/docs/localidades?versao=1

**Comment by omurilo** [comment]
A API do IBGE é bem dahora pra utilizar quanto a pegar as cidades e tal, poderia ser um fallback pra api do INEP;

Conheci ela hoje tentando achar alternativas para a pricez que atualmente está fora do ar.

**Comment by juniorpb** [comment]
@omurilo também pesquisei na anatel dados que relaciona DDD e Cidades, caso encontre alguma boa opção será ótimo.
