### ISSUE TITLE
Erro na função getCitiesByState

### ISSUE THREAD

**Issue by izaiasmachado** [juniorpb/cidades-promise#4]
O erro acontece porque o código não sabe se houve erro no service state, pelo axios ou se o estado digitado realmente não existe. 

Estou trabalhando na resolução, minha ideia foi de criar um arquivo armazenando a sigla de cada estado. Dessa forma, o código vai saber se o estado realmente não existe ou se houve erro no axios.

**Comment by juniorpb** [comment]
resolvido!!
